### ISSUE TITLE
getting 

### ISSUE THREAD

**Issue by MilindDivre** [tejank10/Spam-or-Ham#1]
Traceback (most recent call last):
  File "C:/Machine Learning/spam/calltest.py", line 202, in <module>
    preds_tf_idf = sc_tf_idf.predict(testData['message'])
  File "C:/Machine Learning/spam/calltest.py", line 178, in predict
    result[i] = int(self.classify(processed_message))
  File "C:/Machine Learning/spam/calltest.py", line 170, in classify
    pSpam += log(self.prob_spam_mail)
ValueError: math domain error

calltest is name of my file

**Comment by tejank10** [comment]
`ValueError: math domain error` occurs when the operand for `log` is <= 0.
`self.prob_spam_mail` is defined as:
`self.prob_spam_mail = self.spam_mails / self.total_mails`
It is possible that `self.spam_mails` is 0 in this case.
